### ISSUE TITLE
Import CSV changes all groups to Root in 2.7.7

### ISSUE THREAD

**Issue by stevem6** [keepassxreboot/keepassxc#10574]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Importing a CSV changes every group name to Root in KeePassXC 2.7.7

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Import a CSV
2. Choose fields including a group name
3. Save database

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The group name chosen should show in the left-hand pane

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Every group name is changed to Root as can be seen when showing All entries in Search

## Context
[NOTE]: # ( Give us any additional information you may have. )
Import CSV works perfectly in version 2.7.6 keeping chosen group names

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8
Distribution: AppImage

[NOTE]: # ( Pick choices based on your environment )
Operating System:/Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
Please share a scrubbed version of the csv file that doesn't work. I cannot replicate this.

**Comment by stevem6** [comment]
[test.csv](https://github.com/keepassxreboot/keepassxc/files/14919337/test.csv)
Images from 2.7.7
Group is chosen from the Name column
![Selection_226](https://github.com/keepassxreboot/keepassxc/assets/21204267/cf0a4266-a918-4c73-bd0b-fa3d7c5268ae)
Showing group names are now Root
![Selection_227](https://github.com/keepassxreboot/keepassxc/assets/21204267/6d9c2d75-f7b4-47cc-89a6-cf4d54c3d0ad)
The same file imported to 2.7.6 shows correct group names
![Selection_228](https://github.com/keepassxreboot/keepassxc/assets/21204267/9598c1be-c0ee-4a17-bf22-6487669c6724)

**Comment by droidmonkey** [comment]
Why are you using the same column for group and title? I see the problem, but this method of importing CSV will not scale at all beyond a couple entries.

**Comment by stevem6** [comment]
The CSV file exported from Roboform doesn't have a group field - using the name column for group and title works well in 2.7.6 even for a file with hundreds of entries.

**Comment by droidmonkey** [comment]
You want hundreds of groups?

**Comment by stevem6** [comment]
Not a problem as that's the default in Roboform.

**Comment by michaelk83** [comment]
Was there an option or feature request to import into a group? If not, then I suggest importing everything into the Root group of a new database, and then moving or copying the entries into the group or groups you want.

**Comment by stevem6** [comment]
I may be misunderstanding your suggestion, but 2.7.7 does put everything into the Root group of a new database. It would be a lot of work to then create lots of individual groups and move entries into them. 2.7.6, on the other hand, creates the individual groups automatically.

**Comment by michaelk83** [comment]
My suggestion is if you want a smaller number of groups. A separate group for every item isn't very useful IMO. Might as well just leave them all in the root group in that case.

**Comment by droidmonkey** [comment]
Dang, simple programming error on my part. Fixed in #10575

**Comment by stevem6** [comment]
Thanks!

**Comment by michaelk83** [comment]
> Was there an option or feature request to import into a group?

https://github.com/keepassxreboot/keepassxc/issues/1832#issuecomment-394883762 is the closest I could find to importing into an existing group (just noting it for reference).

**Comment by droidmonkey** [comment]
#1832 was completed with 2.7.7 import wizard.

**Comment by cedric-anamorphik** [comment]
The problem is still present in 2.7.7 import wizard on the KeePassXC-2.7.7-x86_64.dmg release.
(It's OK in 2.7.6)
