### ISSUE TITLE
The option "I have a key file" doesn't work

### ISSUE THREAD

**Issue by gbschenkel** [keepassxreboot/keepassxc#10721]
## Overview
The option to unlock the database using a key file, doesn't work on version 2.7.8.

## Steps to Reproduce
1. Install or upgrade to version 2.7.8
2. Load a locked database
3. Click on "I have a key file"

## Expected Behavior
A field to insert the path of the file or a windows to select the file from the File Dialog.

## Actual Behavior
Nothing happen when clicking the link/option.

## Context
I need to open the database using a key file which I can't insert anywhere.
On 2.7.7 it works as expected.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.8
Revision: f6757d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows and Linux
Desktop Env: Win10 and KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Works 100% for me on all platforms

You can try circumventing your issue by using the command line flag: `keepassxc.exe --keyfile c:\my\path\key.keyx`

**Comment by ecureuill** [comment]
I can reproduce it on 2.7.8 for MacOS

https://github.com/keepassxreboot/keepassxc/assets/993369/06394a0b-3727-4c3a-bfa2-3f021d6941a6

**Comment by droidmonkey** [comment]
Looks like a translation connected issue potentially. @phoerious

**Comment by ecureuill** [comment]
This error just happens on my new laptop's user. 
On old user, key-file feature still works

**Comment by phoerious** [comment]
Yes, I think the translator messed up the string. This should be a green link. I can reproduce the behaviour by switching the language to "Portuguese (Brazil)". Perhaps a workaround for now is to switch to "Portuguese (Portugal)" instead.

**Comment by phoerious** [comment]
I checked the Transifex translations. In the 2.7.x stable version it was correct, but the develop resource was indeed missing the tags, which I fixed. I'm not sure why this made it into 2.7.8 then, but perhaps they realised their mistake and already corrected it in one of the resources.

EDIT: The history certainly looks like that's what's happened:

<img width="353" alt="image" src="https://github.com/keepassxreboot/keepassxc/assets/911270/e0a60db5-f596-4474-b49e-3c53fffd1d84">

Anyway, this will now be fixed with the next release.

**Comment by michaelk83** [comment]
Since this seems to affect key functionality in a potentially breaking manner, wouldn't it be best to leave the HTML tags outside of the translation string?

**Comment by phoerious** [comment]
Perhaps, though Transifex also shows a warning if you forget to include them.

**Comment by droidmonkey** [comment]
I am in favor of a change that pushes the HTML outside the translation, for this case. We don't expect translators to move the tags around since the entire text is the link.

**Comment by hmykle** [comment]
Problem still valid for the Norwegian translation. Have to switch back to English for the link to work. I use latest version v2.7.11.
