### ISSUE TITLE
Keepassxc 2.7.10 on macOS is often stuck in "secure input" mode

### ISSUE THREAD

**Issue by gerritgriebel** [keepassxreboot/keepassxc#11906]
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

I'm using the utility Keyboard Maestro to automate things in macOS. It can not read keystrokes when macOS is in "secure input" mode. The Keyboard Maestro Editor app shows a warning, that "secure input" is currently active:

> Secure Input is enabled which means the system thinks you are currently in a password field and will not allow applications to monitor the keyboard.
> This will stop Typed String triggers from working, as well as stop Keyboard Maestro from sensing your keystrokes while setting hot keys.
> You will need to find the offending application (probably KeePassXC) and quit it.

Restarting Keepaasxc always helps in this situation. 

### Steps to Reproduce

I can reproduce the desired behavior, when I'm editing a password in KeePassXC. But I can unfortunately not reproduce the unintended "secure input" when KeePassXC is not prompting passwords. I happens a few times a day.

### KeePassXC Debug Information

```Text

```

### Operating System

macOS

### Linux Desktop Environment

None

### Linux Windowing System

None

**Comment by droidmonkey** [comment]
This is 100% intentional 

> I can reproduce the desired behavior, when I'm editing a password in KeePassXC. But I can unfortunately not reproduce the unintended "secure input" when KeePassXC is not prompting passwords. I happens a few times a day.

Simply remove keyboard focus on password edit fields to disable secure input again.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/blob/develop/src%2Fgui%2FPasswordWidget.cpp#L234-L236

**Comment by droidmonkey** [comment]
You can detect what app is holding secure input on using this command: `ioreg -l -w 0 | grep SecureInput`

Look for `kCGSSessionSecureInputPID` and then you can run that PID through PS or Activity Monitor to get the app name. We aren't the only game in town enabling secure input mode. I am surprised Maestro Editor calls us out like that since we only _just enabled secure input mode in 2.7.10_

**Comment by gerritgriebel** [comment]
I experience this unintended secure mode behavior only after updating to 2.7.10. I'll keep an eye on it and try to reproduce it. Will report, if I have any new findings. btw. iterm2 shows a key icon whenever secure mode is enabled, convenient for tests.

**Comment by gerritgriebel** [comment]
It happens (but not always) when the mac is coming back from sleep mode. I have two databases and both are unlocked.

**Comment by droidmonkey** [comment]
The only time secure input is enabled is when a password input field is focused. Simply focusing and unfocusing the keepassxc window should clear it. If not, editing an entry and focus and unfocus the password field. Same with the unlock screen. Although I could not reproduce the problem on my side.

**Comment by gerritgriebel** [comment]
I tried to resolve the situation by editing a password and leaving the field. It does not help  when this unintended locking after returing from sleep mode appears. The only thing that helps is quitting KeepassXC and starting it again.

**Comment by droidmonkey** [comment]
That really doesn't make sense given how this feature (secure input) is supposed to work. I wonder if there is a macos bug here.

**Comment by gnmerritt** [comment]
I've been having this same problem and can confirm that it happens even when the keepassxc (`2.7.10`) window is not focused (and breaks my iterm2 global hotkey, etc). When I searched for the process holding secure input I got back `loginwindow` in case that is helpful in narrowing down what macOS is up to.

Quitting and restarting keepassxc seems to clear things up. 

```bash
$ uname -a
Darwin NNNN.local 24.3.0 Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:16 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6000 arm64
```

**Comment by droidmonkey** [comment]
Hmmm that might be helpful

**Comment by sandrobraendli** [comment]
I think I can reproduce it: https://github.com/keepassxreboot/keepassxc/pull/11623#issuecomment-2742491959

**Comment by droidmonkey** [comment]
I think i know why, the password field likely never gets to issue an unfocused event before the pop up dialog is hidden. However, still doesn't make sense that focus and unfocus of any other password fiels wouldn't restore input.

**Comment by droidmonkey** [comment]
OK I replicated and figured out a fix, PR inbound

**Comment by rd-danny-fleer** [comment]
@droidmonkey I saw your PR and I'm curious if something is still missing. This bug is really annoying in my daily work because I have to open/close KeepassXC several times a day to make secure input go away.

**Comment by droidmonkey** [comment]
If this disrupts your workflow recommend simply downgrading to 2.7.9 for view.

**Comment by gerritgriebel** [comment]
> If this disrupts your workflow recommend simply downgrading to 2.7.9 for view.

I did so and got message in browser extension: "Sie verwenden eine alte Version von KeePassXC. [Bitte laden Sie die neueste Version von keepassxc.org herunter](https://keepassxc.org/download)." So I wonder how to downgrade Chrome browser extension as well. I did export browser extension settings to keepassxc-browser_settings.json then removed the browser extension from Chrome and reinstalled the extensions current version. It worked fine until I did import keepassxc-browser_settings.json, after that I got the same message again about outdated KeePassXC. How to downgrade browser extension properly?

**Comment by droidmonkey** [comment]
Disable the update notice in the browser extension settings or ignore it

**Comment by lovromazgon** [comment]
@droidmonkey would it be possible to cut a patch release that includes the fix for this bug? 🙏  This one is very annoying for anyone using hot-keys, and the fix has been around for more than 3 months.

**Comment by droidmonkey** [comment]
Yes we will... been tied up lately.

For now, recommend being careful when using browser extension or auto type unlock database dialogs. Ensure you unfocus from the password field before pressing unlock.

**Comment by gnmerritt** [comment]
Unfortunately I believe this issue is not completely fixed - I am still running into problems after a reboot where secure input is incorrectly being set and blocking my iTerm global hotkey from working. It seems to happen immediately post reboot and before I have unlocked or focused keepassxc at all (it has been auto-launched and is somewhere in a whole pile of newly started windows). If I quit keepassxc the problem goes away, so I am fairly certain its the culprit. 

I am on a snapshot build so I can also confirm that the issue is better than on 2.7.10. Happy to provide any other info or a more specific reproduction path if that'd be helpful. 

```
$ brew info keepassxc@snapshot
==> keepassxc@snapshot: 2.8.0,267966
https://keepassxc.org/
Deprecated! It will be disabled on 2026-09-01.
Installed
/opt/homebrew/Caskroom/keepassxc@snapshot/2.8.0,266583 (118.1MB)
  Installed using the formulae.brew.sh API on 2025-07-31 at 10:45:21
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/k/keepassxc@snapshot.rb
...
$ uname -a
Darwin ----.local 24.6.0 Darwin Kernel Version 24.6.0: Mon Aug 11 21:16:21 PDT 2025; root:xnu-11417.140.69.701.11~1/RELEASE_ARM64_T6000 arm64
```

**Comment by droidmonkey** [comment]
Not sure what snapshot build that is. Get it directly from us: https://snapshot.keepassxc.org

**Comment by gnmerritt** [comment]
I checked the formula (https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/k/keepassxc@snapshot.rb) before using it, as far as I can tell it's pulling from your snapshot server and the snapshot build I was on is `266583`. 

In any case, just confirmed the issue w/ the latest snapshot dmg (267966, commit `c0ea6f6`):

1. reboot
2. log in, keepassxc starts along with a bunch of other things (firefox, spotify, etc) and is not visible. I have 3 desktops and keepassxc starts on the middle one
3. iterm global hotkeys are blocked by secure input, start working when I quit keepassxc

debug info from the snapshot build is:

```
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: c0ea6f6

Qt 5.15.16
Debugging mode is disabled.

Operating system: macOS 15.7
CPU architecture: x86_64
Kernel: darwin 24.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.8.1
```

**Comment by jhass** [comment]
Maybe the same or related, I see secure input activated even when there's just a pending touch ID unlock

**Comment by droidmonkey** [comment]
> Maybe the same or related, I see secure input activated even when there's just a pending touch ID unlock 

This wouldn't be related to us. That dialog is managed by the OS.

**Comment by jhass** [comment]
Sorry I haven't been clear, I'm seeing it when keepassxc is showing the unlock with touch ID database lock screen, without any password input field, prior to the OS native dialog you get when pressing that button.

**Comment by kiprasmel** [comment]
fwiw, I've had the same issue as @gnmerritt re: secure input blocking e.g. iterm shortcuts.

in my case, keepass was asking for input & was  de-focused, which i suspect could be related to yabai (window manager) not managing it properly, or keepass simply asking not to be managed.

but also another time, it was when the database was locked, i clicked the browser extension to fill the password, it took focus away from current window to keepass, but didn't focus it.

what helped was killing keepass' process, and the issue hasn't occured since

**Comment by droidmonkey** [comment]
We know of the above. That is this issue, which has been corrected for next release. If you are running the 2.8.0 snapshot build and _still having problems_ then I need to know more to find the trigger.

**Comment by gnmerritt** [comment]
I've been able to reproduce on the snapshot build by logging in/out, happens consistently. I've added some logging and am trying to reproduce with a from-source build now...

**Comment by gnmerritt** [comment]
Alright I'm not sure what to make of this. I've added logging and have confirmed that the event filter is getting a `QEvent::FocusIn` event (and then turning on secure input protection) on login, even when the window is one desktop over and definitely not focused. 

Attached the diff w/ my logging and the output in case anyone else has an idea, I'm happy to try more logging or mitigation now that I can reproduce reliably. 

[logging.txt](https://github.com/user-attachments/files/22471916/logging.txt)

[login-secure-set3.log](https://github.com/user-attachments/files/22471918/login-secure-set3.log)

**Comment by droidmonkey** [comment]
If that's the case, then simply focusing a password field and unfocusing it should disable secure input. 

FocusIn will only ever be triggered when the QWidget (and hence the application) has keyboard focus. Unless there is a bug in qt?

**Comment by gnmerritt** [comment]
this is definitely happening when I have my keyboard focus elsewhere. during that entire log file I never once have keepassxc focused or even visible on the same desktop and it still receives a `QEvent::FocusIn`. It's not a showstopper bug or anything but it is annoying, I'll try digging around the QT/multiple desktops angle when I get some more time in a day or two

**Comment by droidmonkey** [comment]
I simply cannot replicate the scenario where secure input is "stuck on" with the 2.8.0 snapshot build. Every time I defocus from KeePassXC, my detector script makes it clear that it is not enabled.

Create a file `secure-input.sh` and paste this in:

```
#!/bin/zsh

for i in {1..10}; do
    echo "Detecting secure input..."
    ioreg -l -w 0 | grep SecureInput
    echo
    sleep 2
done
```

Then run that script in a terminal. When KeePassXC is focused on a password field it will output a huge chunk of text. When it is not focused all you will see is "Detecting secure input". Huge text means secure input is enabled.

When logging in, KeePassXC starts and takes the focus (which is expected). When I defocus, secure input is disabled.

**Comment by swdit** [comment]
I run into problems with espanso (auto text replace tool) as soon as KeepassXC is openend.
Propably a similar problem with SecureInput as you experience.

However using the ioreg command it says that the Firefox Browser (eg. the KeepassXC Plugin in Firefox) is blocking the secure input.

As soon as I close the KeepassXC App (but not Firefox) SecureInput is released and espanso is working again.

MacOS 15.5
Keepass App 2.7.10
Keepass BrowserPlugin 1.9.9.6 (2025-09-09)
Firefox 143.0

**Comment by droidmonkey** [comment]
Ok I will try to replicate that scenario

**Comment by gnmerritt** [comment]
> When logging in, KeePassXC starts and takes the focus (which is expected). When I defocus, secure input is disabled.

Yes, though this means every time I log in I have to sift through all my auto started windows on all my desktops to find the keepasxc window and then focus and defocus it before my terminal hotkey works. It's not stuck like on the current release but it's still a ux bug imo.

My repro scenario btw is to pin the snapshot build to the last desktop as well as enabling start on login. It gets a focus event before I go to that desktop and actually focus it. In the log file I posted I never go to the desktop with keepass running on it at all, I just log in, confirm secure input is on and then quit keepass from the toolbar and confirm secure input is off.

**Comment by droidmonkey** [comment]
In my testing there was never a need to focus the keepassxc window and then unfocus it. Please share any other custom apps you have running that could be manipulating window behavior. I suspect you have something unique going on here.

**Comment by gnmerritt** [comment]
I just reproduced again on a fresh user account, only things running were iterm2 with a global hotkey and a from-source keepassxc build pinned to the third desktop. Log in, stay on the first desktop and never focus on keepassxc or even see the window and still it is holding secure input. Secure input gets dropped when I go to the third desktop and focus/unfocus the password field or I quit keepassxc.

**Comment by droidmonkey** [comment]
@swdit 

> However using the ioreg command it says that the Firefox Browser (eg. the KeepassXC Plugin in Firefox) is blocking the secure input.
> 
> As soon as I close the KeepassXC App (but not Firefox) SecureInput is released and espanso is working again.

Could not replicate your issue at all. Please note that when you are focused in on a password field in the browser that the BROWSER will enable secure input mode. You may have had that been the case, then when you quit KeePassXC it unfocused the password field and it appeared like it was us. However, as you mentioned, ioreg pointed to the BROWSER holding the secure input, not keepassxc.

@gnmerritt no matter what I do, I cannot replicate your scenario. Unfortunately there is not much I can offer for your situation besides the focus/unfocus work around. I won't be making any changes to the secure input code.

**Comment by gnmerritt** [comment]
> [@gnmerritt](https://github.com/gnmerritt) no matter what I do, I cannot replicate your scenario. Unfortunately there is not much I can offer for your situation besides the focus/unfocus work around. I won't be making any changes to the secure input code.

Sounds good, I'll file a new issue and take a look at it myself when I get some time in the next couple weeks.

**Comment by venatiodecorus** [comment]
I've run into something similar but it doesn't seem to happen on login. I haven't isolated the event that triggers it, but secure input will get stuck on (as shown in iTerm2, and disabling some of my Logitech mouse's keys for some reason...). I can resolve this by closing and re-opening KeePassXC. I used `ioreg -l -w 0 | grep SecureInput` to identify KeePassXC as the source and have tried restarting the browser to clear it as per some earlier suggestions. It only clears once I restart KP.
