### ISSUE TITLE
[BUG] [2.2.4] Mac Version Download package contains wrong build

### ISSUE THREAD

**Issue by r0ckarong** [keepassxreboot/keepassxc#1279]
I downloaded the 2.2.4 Mac package from the website. Digest with hash ```69ce702d25fb015521714bf6f2542261a65862ec36a176f30e9f612dc27bffb8 ```
checks out ok.

When I run the application it will say 2.2.3 in the about dialog and the debug info pasted below. 
The package info for Mac OS will say 2.2.4. Was there just some of the version info not updated or did something wrong get packaged?

## Expected Behavior
Download 2.2.4 package, install. Run 2.2.4

## Current Behavior
Download 2.2.4 package, install. Runs 2.2.3 (presumably)

## Steps to Reproduce (for bugs)
1. Download Mac OS package from Keepassxc.org (https://github.com/keepassxreboot/keepassxc/releases/download/2.2.4/KeePassXC-2.2.4.dmg)
2. Install package
3. Open KeepassXC
4. Open "About KeePassXC"
5. Open Mac OS "Applications" in Finder, "Get Info" on KeePassXC.app

<img width="1193" alt="screen_shot_2017-12-14_at_12_30_47" src="https://user-images.githubusercontent.com/4920542/33990326-d8bbe226-e0ca-11e7-8e4a-b8ed93a29bcd.png">

## Debug Info

KeePassXC - Version 2.2.3
Revision: cf94610

Libraries:
- Qt 5.10.0
- libgcrypt 1.8.1

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- KeePassHTTP
- Auto-Type

**Comment by droidmonkey** [comment]
That hash corresponds to 2.2.3 as well. @phoerious

**Comment by phoerious** [comment]
Jeez. I'll fix that in the evening.

**Comment by phoerious** [comment]
Fixed. New version is uploaded as 2.2.4-2.

**Comment by r0ckarong** [comment]
I finally got around to installing this new package and it still says 2.2.3 in the About dialog. Did that fix really work?

**Comment by phoerious** [comment]
2.2.4-2 is definitely version 2.2.4. But apart from the stated version, also 2.2.4-1 was really 2.2.4.

**Comment by r0ckarong** [comment]
So how come I still see 2.2.3 in the About dialog? Should I just ignore this?

**Comment by phoerious** [comment]
I can't test it right now, but when I'm pretty sure, I tested it before uploading. https://github.com/keepassxreboot/keepassxc/releases/download/2.2.4/KeePassXC-2.2.4-2.dmg should show you 2.2.4. If it really doesn't, just ignore it. It is 2.2.4 and even if it were 2.2.3, there would be no difference for Mac.
