### ISSUE TITLE
Unable to open the database. Wrong key or database file is corrupt. (Mac)

### ISSUE THREAD

**Issue by kaos2069** [keepassxreboot/keepassxc#1444]
I am truly broken with this....
I really don´t know what could happended, but Ill write the steps, and lets see if someone it is able to help me to recover or open my file...
Basically, I can not access my kdbx, and I did not more than copy and paste in other place... That´s all.

## Steps to Reproduce (for bugs)
1. I created a encrypted dmg in order to copy my data base in there. And I did.
2. I tried to open the file from the dmg (The duplicated one) And was not possible at all. (Same problem than now)
3. I open the Original data base, no problem at all.
4. (this could be a problem) While the Original was open, I tried to open the one (Whit same name, in the mounted dmg) and it was not possible at all. 
5. I close the software (Did not ask about save the Original (Because I did not make any change) and that was the last time I can open my file.......... 
6. I recover the previous database from my Time Machine Backup, but I am not able to open it. I tried with several differents copies restored from Time Machine and doesnt work, but now they are all Time backups, not the Original original... (But all are the same as I did not change it  since 7-10 days)
7. Uninstalled and installed.
8. Password it is correct by 10000000% sure

Can someone explain me how is this possible???
It is possible that KeepassXC it is wrong for some configuration or something and able to open this file in windows or linux version?? I hope to hear something better than what I was thinking all this 5-6 hours trying to recover the damn &$/%"&$/ file....

## DUBUG INFO

KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.3.0

**Comment by droidmonkey** [comment]
Have you tried using regular keepass to open the time machine version?

**Comment by kaos2069** [comment]
Thank you very much for getting interested.
Im not able to run Keepass with Wine. I tried with MacPass and same problem: Password Or Key File wrong.

I tried with the file in key file and without, with Original, Duplicated in dmg and Time Machine Version (Actual Version of the file)

**Comment by phoerious** [comment]
What's the modification date of your time machine backup?

**Comment by kaos2069** [comment]
Downloading Mono, if not tomorrow trying in a PC.

That could be interesting. The file I have now, it is from 23th January Modified (The last change)
But I got previous ones, like 2 January and thats totally fine, because I just order things, but not any loss. I will try with that one but one question:
If I have the file backup, the file should be fine, I am wrong in this? 
Or there is some attachment to the machine-filelocation-folder itself? 

I am really getting mad trying to understand the mistake, as logically I can not find it at all and get me more crazy... I can not simply copy the file, and put it whatever or what?
Again, password, it can not be bad because it is a secuence that I usefor other encryption and the Keyboard I check the language.. As I said.. getting mad.

**Comment by phoerious** [comment]
If you can't open it with MacPass, it's unlikely you can open it with KeePass, but you may try nevertheless.

If you have a file with modification date older than your "accident", you should be able to open it. Make sure

a) you enter the correct password (obviously)
b) with the correct keyboard layout (if in doubt, make the password visible)
c) if you used a key file, with exactly that key file
d) if you used a YubiKey, insert it

For b), c) and d) make sure the corresponding checkbox is checked.

If all these obvious mistakes are ruled out and you can't still open it, your database has probably been corrupted. We had a corruption issue prior to 2.2.4, but it has been fixed since then, so either this is unrelated or you discovered another issue.

Corruption can only occur if the database file is being written to. This happens only if you click save or if auto-reload is turned on. Please check if that's the case.

Copying the file around is not a problem, unless there is some weird operating system-specific interaction between copying the file and auto-reload (highly unlikely, but not impossible). Copying or moving the file around while it's not opened in KeePassXC is always safe.

**Comment by kaos2069** [comment]
Yes it is Auto-reload, but I can still not getting why I can not open previous days file with the same name... I can just not understand.... 
![screen shot 2018-02-01 at 00 29 52](https://user-images.githubusercontent.com/36014689/35653162-1c190372-06e7-11e8-8002-3bb525ea784c.png)
Thank you very much for your help, much appreciated :)

I tried to do what your recommend, and I restored a 2nd Jan version and no possible.. :(

I am thinking to make a full restore with time Machine as well, in case something get inside somewhere I don´t know how... It is just crazy..

**Comment by phoerious** [comment]
No, there is no reason to do a full restore. Either a database can be opened or not. There is no other system interaction.
It's indeed strange that your backups seem to be corrupt as well, especially if you were able to open your database only days ago. I don't really have an answer for that.

**Comment by kaos2069** [comment]
My apologies... It is working... It was my stupid blindness yesterday... 
Today it was matter of minutes to realise than the key It was not correct.. I created a hidden folder and the one the system was accessing was the last one, not this one, after trying that much times, and I completely forgot it yesterday... 6h blind and frustrated.. xD

Well at least happy end for me, so sorry to bother and so much appreciated for instructions, as every troubleshooting, I learn a lot, so thank for your support in my stupid mind problem.

Regards

**Comment by phoerious** [comment]
Glad your database is still alive. Would have been tragic if we still had corruption issues.

**Comment by ryantanner14** [comment]
For others as foolish as myself, here’s another troubleshooting step. I reset the key in KeepassXC because mine was going to be legacy, however in doing so, I only checked the box that said key reset, I assumed that the password would remain unchanged, however, this only made it so that I didn’t have a password, so it took me a couple days to figure out that it was as simple as using the new keyfile and just leaving the password field blank and then I could access my database again. Hopefully that helps out anyone who is in my same situation.

**Comment by ChazSedona** [comment]
I am running keepassx 0.4.3, didn't know about upgrades. The other day I opened it to retrieve a password, closed it the about an hour later went to open it and it read New and all the old data is not visible. I can't seem to get Time machine to open the old app. this is going back to Mar 29.
I tried going back to Mar 25 on Time Machine but it just doesn't open the app as per that date.

**Comment by phoerious** [comment]
KeePassX 0.4.3 uses a totally different file format. You have to import it via File/Import/From KeePass1.

**Comment by ChazSedona** [comment]
Janek,
	I’m not sure I’m following you. How do I find the file on Time Machine or is it still in iMac somewhere?
		thanks, Chaz

**Comment by ChazSedona** [comment]
Janek,
	where did you go? I am really lost here.
thanks, Chaz

On Apr 7, 2019, at 12:41 AM, Janek Bevendorff <notifications@github.com> wrote:

> KeePassX 0.4.3 uses a totally different file format. You have to import it via File/Import/From KeePass1.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



----

**Comment by droidmonkey** [comment]
Chaz we have absolutely no idea what your problem is, where your database is stored, or how to help you. In very specific terms (put it in a list) describe EXACTLY what you did and how you did it. What programs you are using. Etc.

**Comment by ChazSedona** [comment]
Jonathan,
	I have been running  KeePassX 0.4.3on iMac 10.9.5 and Time Machine storage on a MyPassport ext drive.
About a week ago, I opened KeePassX to retrieve a password, that went fine, then a couple hours later went to open it again and the screen said (New) at the top and everything was gone.
	I have tried to go back in TimeMachine to say Mar 25 to retrieve the app as it was but that doesn’t seem to work.
	i wasn’t aware of KeePassX updates because I just don’t need to use it very often and it always worked. 
		P.S.This is the first time I have ever had an app crash on a Mac.
		thanks, Chaz

On Apr 9, 2019, at 9:50 AM, Jonathan White <notifications@github.com> wrote:

> Chaz we have absolutely no idea what your problem is, where your database is stored, or how to help you. In very specific terms (put it in a list) describe EXACTLY what you did and how you did it. What programs you are using. Etc.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



----

**Comment by phoerious** [comment]
KeePassX is not KeePassXC. You cannot open files created in KeePassX 0.4.3 in KeePassXC. You have to use "File/Import from KeePass1" for that to convert the kdb file to a kdbx file.

**Comment by ChazSedona** [comment]
I didn’t upgrade to XC at all.

On Apr 9, 2019, at 10:41 AM, Janek Bevendorff <notifications@github.com> wrote:

> KeePassX is not KeePassXC. You cannot open files created in KeePassX 0.4.3 in KeePassXC. You have to use "File/Import from KeePass1" for that to convert the kdb file to a kdbx file.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



----

**Comment by phoerious** [comment]
Well, you couldn't have opened your file in KeePassXC before.

**Comment by ChazSedona** [comment]
KeePassX 0.4.3  is the one that crashed upon opening.

On Apr 9, 2019, at 2:52 PM, Chaz <chaz@cybertrails.com> wrote:

> I didn’t upgrade to XC at all.
> 
> On Apr 9, 2019, at 10:41 AM, Janek Bevendorff <notifications@github.com> wrote:
> 
>> KeePassX is not KeePassXC. You cannot open files created in KeePassX 0.4.3 in KeePassXC. You have to use "File/Import from KeePass1" for that to convert the kdb file to a kdbx file.
>> 
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
> 



----

**Comment by droidmonkey** [comment]
We cannot help you with issues related to KeePassX 0.4.3. It is not our program.

**Comment by ChazSedona** [comment]
who’s program is it?

On Apr 9, 2019, at 4:16 PM, Jonathan White <notifications@github.com> wrote:

> We cannot help you with issues related to KeePassX 0.4.3. It is not our program.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



----

**Comment by droidmonkey** [comment]
https://www.keepassx.org/

**Comment by ChazSedona** [comment]
got on that forum.   thanks

On Apr 9, 2019, at 6:36 PM, Jonathan White <notifications@github.com> wrote:

> https://www.keepassx.org/
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



----

**Comment by phoerious** [comment]
KeePassX is abandoned. KeePassX 0.4.3 even more so.
