### ISSUE TITLE
libsodium18 tries to overwrite libsodium23 installed by another package

### ISSUE THREAD

**Issue by rvbhute** [keepassxreboot/keepassxc#1513]
I have installed KeepassXC from PPA and also PHP packages from deb.sury.org  PPA. Running a routine upgrade gave the following error.

````
Reading package lists... Done                    
Building dependency tree       
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  libsodium18
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
45 not fully installed or removed.
Need to get 0 B/435 kB of archives.
After this operation, 1,481 kB of additional disk space will be used.
(Reading database ... 394601 files and directories currently installed.)
Preparing to unpack .../libsodium18_1.0.16-0ppa1~xenial1_amd64.deb ...
Unpacking libsodium18:amd64 (1.0.16-0ppa1~xenial1) over (1.0.14-1+ubuntu16.04.1+deb.sury.org+1) ...
dpkg: error processing archive /var/cache/apt/archives/libsodium18_1.0.16-0ppa1~xenial1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libsodium.so.23.1.0', which is also in package libsodium23:amd64 1.0.16-2+ubuntu16.04.1+deb.sury.org+3
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libsodium18_1.0.16-0ppa1~xenial1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

rohit@ryujin ~ $ apt policy libsodium18
libsodium18:
  Installed: 1.0.14-1+ubuntu16.04.1+deb.sury.org+1
  Candidate: 1.0.16-0ppa1~xenial1
  Version table:
     1.0.16-0ppa1~xenial1 500
        500 http://ppa.launchpad.net/phoerious/keepassxc/ubuntu xenial/main amd64 Packages
 *** 1.0.14-1+ubuntu16.04.1+deb.sury.org+1 100
        100 /var/lib/dpkg/status
     1.0.8-5 500
        500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages

rohit@ryujin ~ $ apt policy libsodium23
libsodium23:
  Installed: 1.0.16-2+ubuntu16.04.1+deb.sury.org+3
  Candidate: 1.0.16-2+ubuntu16.04.1+deb.sury.org+3
  Version table:
 *** 1.0.16-2+ubuntu16.04.1+deb.sury.org+3 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status

````

## Expected Behavior
libsodium18 should update from the 1.0.14 version installed by deb.sury to 1.0.16 version installed by KeepassXC.

## Current Behavior
libsodium18 is try to overwrite files owned by libsodium23 package.

## Steps to Reproduce (for bugs)
1. Your system has both KeepassXC and deb.sury.org PPAs, and you have KeepassXC and PHP packages installed.
2. Run `apt update` and then `apt full-upgrade`.

## Context
I cannot update my system fully. I will need to remove PHP packages from my system.

## Debug Info
KeePassXC - 2.2.4-0ppa1~xenial1

Libraries:
- libsodium

Operating system: Linux Mint 18.3
CPU architecture: amd64
Kernel: 4.13.0-32-generic

**Comment by phoerious** [comment]
Our package is an upgraded Artful package. Apparently, the binary version changed without us noticing. It should not install as libsodium.so.23.1.0.
If both packages, can co-exist, we may as well upgrade to libsodium23 as well.

**Comment by phoerious** [comment]
Fixed in https://github.com/keepassxreboot/keepassxc-packaging/commit/54fe397f29ddb214e4f45c21cbc1edaaf17b7170
Builds should be available within the next hours.

**Comment by scde** [comment]
Hi,

I think my problem is related to this that is why I am not opening a new issue.
I have version 2.2.4-0ppa1\~xenial1 of KeePassXC installed on Ubuntu 16.04.

This last update to libsodium overwrote my libsodium18 package from the Ubuntu repositories (had this installed for mpv, ffmpeg, etc.) with what I think is the version libsodium23 from the KeePassXC repo.
From the apt history log: `libsodium18:amd64 (1.0.8-5, 1.0.16-0ppa1~xenial1)`

Now mpv doesn't find libsodium any more:
`mpv: error while loading shared libraries: libsodium.so.18: cannot open shared object file: No such file or directory`
because libsodium18 in the ppa seems to install the 23 version:
```
$ ll /usr/lib/x86_64-linux-gnu/libsodium.so.*
lrwxrwxrwx 1 root root   19 Feb 22 03:32 /usr/lib/x86_64-linux-gnu/libsodium.so.23 -> libsodium.so.23.1.0
-rw-r--r-- 1 root root 1,9M Feb 22 03:32 /usr/lib/x86_64-linux-gnu/libsodium.so.23.1.0
```

And here is what apt reports:
```
$ apt policy libsodium18 libsodium23
libsodium18:
  Installed: 1.0.16-0ppa1~xenial1
  Candidate: 1.0.16-0ppa1~xenial1
  Version table:
 *** 1.0.16-0ppa1~xenial1 500
        500 http://ppa.launchpad.net/phoerious/keepassxc/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.8-5 500
        500 http://de.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
libsodium23:
  Installed: (none)
  Candidate: 1.0.16-0ppa2~xenial1
  Version table:
     1.0.16-0ppa2~xenial1 500
        500 http://ppa.launchpad.net/phoerious/keepassxc/ubuntu xenial/main amd64 Packages
```
You can see that the libsodium23 is not installed but comes indeed from the libsodium18 package.
Maybe there is still some reference in the PPA that points it to libsodium18 or is this intended/a problem on my end?

Thanks in advance and have a nice day =)

**Comment by phoerious** [comment]
libsodium18 doesn't exist in our PPA anymore. Please reinstall libsodium18 from the Ubuntu repository and then tray installing KeePassXC again.

**Comment by scde** [comment]
I did a downgrade, reinstall (complete ppa-purge with uninstall & autoremove) and `apt clean` (because I noticed `libsodium18_1.0.16-0ppa1~xenial1_amd64.deb` was cached) but still get the package listed as upgradable:
```
$ apt list --upgradable
Listing... Done
libsodium18/xenial 1.0.16-0ppa1~xenial1 amd64 [upgradable from: 1.0.8-5]
```

Another thing I noticed are [those](https://github.com/keepassxreboot/keepassxc-packaging/search?utf8=%E2%9C%93&q=libsodium18&type=) references to libsodium18 in the packaging git repo. Could this cause some issue (seems to be a long shot because I do **not** have libsodium-dev installed)?
```
$ apt depends libsodium-dev
libsodium-dev
  Depends: libsodium18 (= 1.0.16-0ppa2~xenial1)
```
This does reference libsodium18 but has the package version of libsodium23 (`1.0.16-0ppa2~xenial1`). Weirdly it does want to upgrade me to the version `1.0.16-0ppa1~xenial1`.

Now when I upgrade (which does work, is this cached on launchpad?) the wrong `libsodium.so.23.1.0` is installed again. Maybe it does some fall-back routine or do I have some weird configuration that might cause this?

**Comment by rvbhute** [comment]
Same as @scde , I purged KeepassXC and its PPA and tried a clean install. It installs KeepassXC, but also says one package upgradeable.

```
rohit@ryujin ~ $ apt list --upgradable -a
Listing... Done
libsodium18/xenial 1.0.16-0ppa1~xenial1 amd64 [upgradable from: 1.0.8-5]
libsodium18/xenial,now 1.0.8-5 amd64 [installed,upgradable to: 1.0.16-0ppa1~xenial1]

rohit@ryujin ~ $ apt policy libsodium18 libsodium23
libsodium18:
  Installed: 1.0.8-5
  Candidate: 1.0.16-0ppa1~xenial1
  Version table:
     1.0.16-0ppa1~xenial1 500
        500 http://ppa.launchpad.net/phoerious/keepassxc/ubuntu xenial/main amd64 Packages
 *** 1.0.8-5 500
        500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        100 /var/lib/dpkg/status
libsodium23:
  Installed: 1.0.16-2+ubuntu16.04.1+deb.sury.org+3
  Candidate: 1.0.16-2+ubuntu16.04.1+deb.sury.org+3
  Version table:
 *** 1.0.16-2+ubuntu16.04.1+deb.sury.org+3 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.16-0ppa2~xenial1 500
        500 http://ppa.launchpad.net/phoerious/keepassxc/ubuntu xenial/main amd64 Packages
````

The PPA page mentions the latest libsodium package as `1.0.16-0ppa2~xenial1` but this is not seen in the apt policy output above. I tried after emptying `/var/lib/apt/lists` but got the same result.

**Comment by phoerious** [comment]
Alright, this should really be fixed now. libsodium-dev now depends on libsodium23 and I deleted libsodium18 from the PPA (again?). It still shows up when you do an apt update, but I hope it'll be gone in a few hours or so.
I tested adding both the mentioned PHP PPA and ours and was able to successfully install KeePassXC without running into conflicts with their libsodium23.

**Comment by phoerious** [comment]
Update: the faulty libsodium18 seems to be gone now.

**Comment by scde** [comment]
Can confirm. All seems to work and install correctly for me.

Thank you very much and good luck with the new release. Looks to be a very exciting :)
