### ISSUE TITLE
Open other database URL entry

### ISSUE THREAD

**Issue by pquerner** [keepassxreboot/keepassxc#1536]
## Expected Behavior
On Windows Original "KeePass" Variant you could make a link to another Keepass database file with
kdbx://C:\database.kbdx. If you double click that entry's URL it would open the database file. (Even is password protected, the password would come from the entry and would be passed in the openening process silently.
It also worked for password+keychain protection, but that didnt come right out of the box. (But I think I have the settings on my windows maschine still and could share it)
 
## Current Behavior
This feature isnt implemented to my knowledge.

## Context
With the implementation of this feature you could have seperated keepass database files for each customer in a company for instance. A "master" keepass file would be created with link entries to the customers keepass files. 1 entry = 1 customer = 1 keepass file.
If that keepass file is on an smb share for instance, it would be easy to revoke or give access to a keepass database file per user or per group. If you double click that entry and have ro/rw rights to that file, keepassxc will open that file (in a new window/tab of keepassxc).

Operating system: Mac OS High Sierra (other systems not checked)

**Comment by TheZ3ro** [comment]
We already implemented autoopen (#477) and it is available in 2.3-beta1. 
This feature will be available in 2.3.0 if you prefer a stable release

**Comment by pquerner** [comment]
I would like to reopen this issue, as I see its not working as intended in my opinion.
Double click the entry still opens a webbrowser, instead of trying to open that relative file first (if it exists of course). 

@TheZ3ro

**Comment by droidmonkey** [comment]
I also cannot get this to work on Windows, and this feature is entirely undiscoverable without studying the original PR.

**Comment by pquerner** [comment]
#1541 better describes this I think. Wierd that I had this opened twice, I am sorry. If I read it correctly, both of the issues mean the same thing.

**Comment by pquerner** [comment]
KeePassXC - Version 2.4.0-snapshot
Build Type: Snapshot
Revision: f06742c


Now allows the database to be opened by having this as the URL ```file:///Users/pq/projects/intern/keepassxc/1.kdbx```, however it still doesnt pass the password to the database.

**Comment by droidmonkey** [comment]
The functionality you are talking about would be AutoOpen or the upcoming group sync.

**Comment by pquerner** [comment]
No AutoOpen seems to do just fine-ish. This is a different problem here.
I do not want files to AutoOpen for me, instead I want to doubleclick (or CTRL+U) the entry and have it opened up with keepassxc - no password no nothing. Since the entry has the full path to the keepass file with the password I expect that its used for this.

This works fine when I call ```switchToOpenDatabase``` from ```void DatabaseWidget::openUrlForEntry```.
However, this closes (with UI bugs) the current open database and switches to the new database instead.

**Comment by droidmonkey** [comment]
Oh I see. When @phoerious completes his overhaul of the DatabaseTabWidget this will be a lot easier to achieve.

**Comment by mendhak** [comment]
Hi just wondering if there's any movement on this?  I searched for `DatabaseTabWidget` but didn't really understand what I was seeing so I couldn't understand if this is easier to achieve now?  

Is it possible to use the 'Open URL' or something similar to open another KDBX directly, rather than via the AutoOpen feature?  Basically a way of opening other KDBXs occasionally rather than each time I open my own KDBX.  

example: 

![image](https://user-images.githubusercontent.com/746276/83430316-5c76e200-a42d-11ea-8264-14f3eb16e001.png)

**Comment by droidmonkey** [comment]
This feature is about opening a database from a URL

**Comment by droidmonkey** [comment]
I just implemented this for 2.6.0, was actually very easy!

**Comment by mendhak** [comment]
Hey thank _you_  @droidmonkey for implementing!  

Out of curiosity/eagerness I built your branch and at least on Linux it was easy to follow the instructions.  Then I created two test DBs, and in the first DB I created an entry as `kdbx://seconddb.kdbx`. Then I clicked that item, and pressed  `Ctrl Shift U` and it opened a second DB!  I didn't test Windows 10 but hopefully it will work there too.  

![image](https://user-images.githubusercontent.com/746276/83669169-08a10000-a5c9-11ea-8e76-48ba5d0c4ab5.png)


![image](https://user-images.githubusercontent.com/746276/83669046-d7283480-a5c8-11ea-990e-60fe2e57ab05.png)

**Comment by j0wey** [comment]
@mendhak You can also use URL field as you guessed. Just combine it with command line:
`cmd://KeePass.exe "X:\path\to\keepass\database.kdbx" -pw:{PASSWORD}`

For further information see the "Usage Examples" on [this site](https://keepass.info/help/base/cmdline.html) and "Executing Command Lines" [here](https://keepass.info/help/base/autourl.html)
As I stumbeld over this problem just yet I can'T tell on which version thsi was implemented.
