### ISSUE TITLE
High idle CPU usage

### ISSUE THREAD

**Issue by grigorig** [keepassxreboot/keepassxc#2652]
## Expected Behavior

KeePassXC idles at approximately 0% CPU usage.

## Current Behavior

High idle CPU usage of around 2% on Linux/X11 (on an Intel i5-6200U CPU). The KeePassXC process seems to wake up around 60 times per second (according to powertop) even when there is no database open and/or the window is minimzed. This negatively affects battery life.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.3
- libgcrypt 1.8.4

Operating system: Fedora 29 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 4.20.3-200.fc29.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
I've noticed very high CPU usage on Windows 10 under the new 2.4.0 version on several occasions. Although it goes away after I lock and reopen the database.

**Comment by mreppen** [comment]
FWIW, I have the same problem on two computers with KeepassXC 2.4.1.

Anything I can do to troubleshoot?

Lock/reopen does not change anything.

**Comment by droidmonkey** [comment]
Oh this issue referenced here was corrected. High cpu has been reported on macOS, but I strongly believe that it's a qt bug.

**Comment by tmst** [comment]
This is still annoying me on x86/linux.
Linux linux-weh4.suse 4.4.176-96-default #1 SMP

**Comment by droidmonkey** [comment]
You are on an EXTREMELY outdated version of KeePassXC

**Comment by grigorig** [comment]
Well, it's definitely not fixed. Can you point me to the commit(s) that supposedly fix this issue?
I still see at least 1.3% constant CPU usage with 20-60 wakeupsof the keepassxc process per second (according to powertop).

Here's my version info:

KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.11.3
Debugging mode is disabled.

Operating system: Fedora 29 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.0.9-200.fc29.x86_64

**Comment by grigorig** [comment]
KeePassXC seems to do a lot of stuff with file descriptors used for event handling or something. I recorded this with strace:

`
04:37:44.521516 write(6<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8
04:37:44.521928 recvmsg(9<UNIX:[12373511->12374559]>, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
04:37:44.522462 recvmsg(9<UNIX:[12373511->12374559]>, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
04:37:44.522945 poll([{fd=6<anon_inode:[eventfd]>, events=POLLIN}, {fd=9<UNIX:[12373511->12374559]>, events=POLLIN}, {fd=12<UNIX:[12374561->12375074]>, events=POLLIN}, {fd=14<anon_inode:inotify>, events=POLLIN}, {fd=17<UNIX:[12373513->12372980]>, events=POLLIN}, {fd=19<UNIX:[12373515->12373514]>, events=POLLIN}, {fd=21<UNIX:[12373518,"/tmp/.doIUGW/s"]>, events=POLLIN}, {fd=34<anon_inode:inotify>, events=POLLIN}, {fd=35<anon_inode:inotify>, events=POLLIN}], 9, 0) = 1 ([{fd=6, revents=POLLIN}])
04:37:44.523540 read(6<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 16) = 8
04:37:44.523784 recvmsg(9<UNIX:[12373511->12374559]>, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
04:37:44.524112 recvmsg(9<UNIX:[12373511->12374559]>, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
04:37:44.524295 poll([{fd=6<anon_inode:[eventfd]>, events=POLLIN}, {fd=9<UNIX:[12373511->12374559]>, events=POLLIN}, {fd=12<UNIX:[12374561->12375074]>, events=POLLIN}, {fd=14<anon_inode:inotify>, events=POLLIN}, {fd=17<UNIX:[12373513->12372980]>, events=POLLIN}, {fd=19<UNIX:[12373515->12373514]>, events=POLLIN}, {fd=21<UNIX:[12373518,"/tmp/.doIUGW/s"]>, events=POLLIN}, {fd=34<anon_inode:inotify>, events=POLLIN}, {fd=35<anon_inode:inotify>, events=POLLIN}], 9, 13) = 0 (Timeout)
04:37:44.538090 write(6<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8
04:37:44.538426 recvmsg(9<UNIX:[12373511->12374559]>, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
04:37:44.538634 recvmsg(9<UNIX:[12373511->12374559]>, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
04:37:44.538821 poll([{fd=6<anon_inode:[eventfd]>, events=POLLIN}, {fd=9<UNIX:[12373511->12374559]>, events=POLLIN}, {fd=12<UNIX:[12374561->12375074]>, events=POLLIN}, {fd=14<anon_inode:inotify>, events=POLLIN}, {fd=17<UNIX:[12373513->12372980]>, events=POLLIN}, {fd=19<UNIX:[12373515->12373514]>, events=POLLIN}, {fd=21<UNIX:[12373518,"/tmp/.doIUGW/s"]>, events=POLLIN}, {fd=34<anon_inode:inotify>, events=POLLIN}, {fd=35<anon_inode:inotify>, events=POLLIN}], 9, 0) = 1 ([{fd=6, revents=POLLIN}])
04:37:44.539284 read(6<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 16) = 8
04:37:44.539458 recvmsg(9<UNIX:[12373511->12374559]>, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
04:37:44.539595 recvmsg(9<UNIX:[12373511->12374559]>, {msg_namelen=0}, 0) = -1 EAGAIN (Resource temporarily unavailable)
`

It repeats like that ad nauseam. As you can see, it polls a bunch of file descriptors all the time and does some reads and writes. I really wonder what these are for.

**Comment by droidmonkey** [comment]
I am looking into this.

**Comment by grigorig** [comment]
FWIW, I have disabled all browser integration functionality. Here's some more info. The wakeup storm starts after the first locking. So, I start up KeePassXC, and it's fine. Wakeups only happen on activity with the UI. I unlock a database, still fine. Wakeups only happen every couple of seconds. But after locking that database - 60 wakeups per second. And they continue if I unlock again.

**Comment by droidmonkey** [comment]
OK that is great info, helps me narrow down the debugging.

**Comment by tmst** [comment]
Debugging this would be a drag. It's no longer acting up on my box and now waking up maybe a few times/min regardless of whether the db is locked. The only things I can think of is that I haven't suspended since the last time I launched it, and that I've installed openvpn which had some dependencies. Maybe something related to Keepass got updated. I'm also running it under alltray, which is quiet as a mouse.

**Comment by m-khvoinitsky** [comment]
Same here. According to top, keepassxc eats about 4% — 6% CPU when does nothing.
* Archlinux
* Qt 5.13.0
* KeepassXC 2.4.3
* Wayland/Sway (but running via xcb/XWayland)
* only Auto-Type is enabled

**Comment by e00E** [comment]
I am experiencing this issue. Same setup as the poster above me, but everything up to date.

**Comment by droidmonkey** [comment]
Fixed in 2.5.1

**Comment by m-khvoinitsky** [comment]
The problem still exists in 2.5.3.

**Comment by m-khvoinitsky** [comment]
What I've found that is only happening when using Breeze theme. I'm using qt5ct, not sure if it matters.
Other Qt application with Breeze theme are not affected.

**Comment by droidmonkey** [comment]
Considering a platform plugin (theme) does not impact the functions of our code base or sure seems like a Qt bug. Understand your assertion about other apps, not they may not be using the affected code.

**Comment by coiby** [comment]
> What I've found that is only happening when using Breeze theme (CPU usage is about 5%, strace is flooding with something similar to [#2652 (comment)](https://github.com/keepassxreboot/keepassxc/issues/2652#issuecomment-493298827), with other theme strace output is silent, CPU usage is zero). I'm using qt5ct, not sure if that matters.
> 
> UPD: not only Breeze is affected, but the behaviour is different depending on theme:
> Affected themes:
> 
> * Breeze
> * Oxygen
> * CDE (but now strace is showing constant calling to `stat` of `/etc/localtime` instead of polling some fd)
> * Motif (same as with CDE)
> * ...
> 
> Unaffected themes:
> 
> * Windows
> * Fusion
> * ...
> 
> Other Qt application with this themes are not affected.

I also used qt5ct. I can confirm the theme Windows doesn't have this issue and adwaita theme can also reproduce this issue.

**Comment by m-khvoinitsky** [comment]
> Considering a platform plugin (theme) does not impact the functions of our code base it sure seems like a Qt bug. Understand your assertion about other apps, but they may not be using the affected code in those plugins.

I'm sorry for bothering you with this again but may be you can help debugging it and report the problem to the right people?

**Comment by droidmonkey** [comment]
I dont have time to do that unfortunately

**Comment by ivankovnatsky** [comment]
also experienced that from time to time, as a first guess it cpu usage would go up after sleep, but the app itself becomes unresponsive, and i have to terminate it to use it.

**Comment by abraxxa** [comment]
Same here. Seems to occur every time I lock sway.
