### ISSUE TITLE
Minimize on startup setting is broken on macOS

### ISSUE THREAD

**Issue by julianschacher** [keepassxreboot/keepassxc#2653]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

I have KeePassXC in my Login Items with Hide enabled:

<img width="780" alt="screenshot 2019-01-27 at 04 59 57_keepassxc_login_item_hide_enabled" src="https://user-images.githubusercontent.com/26492670/51796353-d9b69500-21f0-11e9-89d8-2f177d99b0c5.png">

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

KeePassXC shouldn't show any window after login.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

KeePassXC shows the "Enter master key"-window after login.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

Not show the window. I'm not familiar with the codebase, so that's the most I can say here.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )

0. Use macOS
1. Go to System Preferences -> Users & Groups -> Your user -> Login Items
2. Add KeePassXC to the Login Items and check the Hide-checkbox
3. Log out and in again
4. Observe KeePassXC showing the "Enter master key"-window

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

I'm having a bunch of applications start up after login and having some of them not hide, even tho the hide-option is enabled, is quite annoying.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS 10.14
CPU architecture: x86_64
Kernel: darwin 18.2.0

**Comment by droidmonkey** [comment]
This is likely due to: 
https://github.com/keepassxreboot/keepassxc/blob/develop/src/core/Bootstrap.cpp#L105

Which in your case I recommend enabling the "Minimize on Startup" setting:
![image](https://user-images.githubusercontent.com/2809491/51801074-05447a00-2207-11e9-8be4-4fabdcc51049.png)

**Comment by droidmonkey** [comment]
We may want to not include the bring to front code on MacOS due to the OS supporting hiding windows. Although it would seem the OS does a terrible job at actually hiding the window!

**Comment by droidmonkey** [comment]
Yup that setting is indeed broken on MacOS!

**Comment by finderAUT** [comment]
The setting also does not work on Fedora 29 (with Gnome 3.30.2)

KeePassXC - Version 2.4.0

Libraries:

Qt 5.11.3
libgcrypt 1.8.4
Operating system: Fedora 29 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.0.4-200.fc29.x86_64

Enabled extensions:

Auto-Type
Browser Integration
SSH Agent
KeeShare (only unsigned sharing)
YubiKey

**Comment by droidmonkey** [comment]
The problem on macOS is that this cannot be fixed (easily) without disabling the "click dock icon, restore window" behavior. This is going to require some form of a refactor.

**Comment by g0r3** [comment]
Also broken on my system since quite a while now

`KeePassXC - Version 2.4.1 (and also 2.4.0)
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.0.7-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4`

**Comment by intika** [comment]
the fix is here https://github.com/keepassxreboot/keepassxc/pull/3835

**Comment by droidmonkey** [comment]
Fixed in 2.6.0!

**Comment by TankedThomas** [comment]
I started using KeePassXC on my Mac (10.14.6) as of version 2.6.3 and have this issue even after upgrading to 2.6.4.
No issue with this on Win10 and Arch. Not sure what else I can really add, as I don't see any settings that should affect this behaviour which aren't already enabled, and the issue was considered fixed (which it isn't for me).

**Comment by phoerious** [comment]
I believe Big Sur broke something. It is indeed not working as intended.

**Comment by TankedThomas** [comment]
I upgraded from Mojave 10.14.6 to Catalina 10.15.7 and this issue remains present. I haven't touched Big Sur, so I don't follow on Big Sur being the issue.

**Comment by droidmonkey** [comment]
This is fixed in 2.7.0
