### ISSUE TITLE
[PRE-RELEASE] In macOS dark mode, tab display colors are wrong (2.4.0-beta2)

### ISSUE THREAD

**Issue by tomhundt** [keepassxreboot/keepassxc#2740]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )
When MacOS is set to "dark mode" theme (System Prefs > General > Appearance: Dark), **KeepassXC will display its currently selected tab in black text on almost-black** background (basically unreadable).  Any **unselected tab(s) display in black on light grey** (readable but ugly, and not in keeping with theme).  

## Expected Behavior
All tabs are readable, and the selected one even moreso by being highlighted.

(using Finder as model)

**1. App has focus**
- display the selected tab in white on dark grey
- display unselected tabs in grey on "almost-black" (very dark grey)
![finder focused](https://user-images.githubusercontent.com/12475662/53371596-7f027d00-3905-11e9-91b4-b302f9741c6f.png)

**2. App does not have focus**
- display the selected tab in white on dark grey
- display unselected tabs in grey on "almost-black" (very dark grey)
![finder defocused](https://user-images.githubusercontent.com/12475662/53371608-86298b00-3905-11e9-8de8-d8163001932d.png)

Note that all the grey levels get lighter by a shade, when focus is gained.

## Current Behavior

**1. KeePassXC has focus**
- current tab displays as black text on almost-black background
- unselected tabs display as black text on light grey background

![keepass focused](https://user-images.githubusercontent.com/12475662/53371717-db659c80-3905-11e9-8bae-2c9465b21d3e.png)

**2. KeePassXC does not have focus**
- current tab displays as black text on almost-black background
- unselected tabs display as black text on light grey background

![keepass defocused](https://user-images.githubusercontent.com/12475662/53371735-e4ef0480-3905-11e9-9bc3-bcfea1570fb8.png)

Note that the appearance of the selected tab does not change at all with gain/loss of focus.
Note that the grey levels in the tabs actually get a shade _darker_ with gain of focus.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
* Most important: Change the color of the selected tab's text to be white.
* Change the color of the unselected tabs' text to be grey.  
* Change the color of the unselected tabs' background to be dark grey.

Related (closed) bug: [Dark Mode on macOS 10.14 makes texts barely readable](https://github.com/keepassxreboot/keepassxc/issues/2040)

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open KeePassXC
2. Open more than one .kdbx file (so that selected and unselected tabs are both visible)
3. In System Preferences > General > Appearance, toggle back and forth between Light and Dark.
4. While doing so, select (focus) and deselect the application.  Note its appearance.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Nothing special; I use the program all day long with multiple databases open, but that's probably a typical use case.  Personal + Work + Work#2 + free work done for relatives + government secrets...

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.0-beta2
Build Type: PreRelease
Revision: 9bc20f0

Libraries:
- Qt 5.12.0
- libgcrypt 1.8.4

Operating system: macOS 10.14
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

**Comment by droidmonkey** [comment]
Confirmed, but that is very strange because we don't enforce any specific colors on the tabs. I think this is really a Qt bug. (also I need to test multiple databases on MacOS more often haha)

**Comment by droidmonkey** [comment]
I created an issue: https://bugreports.qt.io/browse/QTBUG-74065

**Comment by sebflipper** [comment]
This also now applies to the latest stable v2.4.0 release, and looks like it has been fixed/merged in the upstream Qt library in [256664](https://codereview.qt-project.org/#/c/256664/).

**Comment by droidmonkey** [comment]
Gonna be a while until this is deployed they put it in Qt 5.13

**Comment by stonerl** [comment]
I don't want to hijack this bug, but I guess there is another Qt related bug regarding Mojave. When switching from Light to Dark Mode while KeePassXC is open, all input fields stay white (in Light Mode Colour).

<img width="912" alt="Screenshot 2019-04-06 at 20 22 45" src="https://user-images.githubusercontent.com/2091312/55673579-fd115680-58a9-11e9-8864-05f9dfc5d45e.png">

<img width="912" alt="Screenshot 2019-04-06 at 20 29 00" src="https://user-images.githubusercontent.com/2091312/55673633-cab42900-58aa-11e9-977c-5ce154b4dcbd.png">

**Comment by droidmonkey** [comment]
Just restart the application after switching color schemes. That is a Qt bug.

**Comment by belle-isle** [comment]
Just commenting after upgrading to version 2.4.1 : from the change log I understand this issue could have been solved, but it doesn't seem to be the case. Tab names are still not the right color.

**Comment by phoerious** [comment]
No, we only fixed reference entry colouring. Tab colouring is something Qt needs to fix.

**Comment by zyv** [comment]
This issue is duplicated by #3193, which includes a workaround on how to disable broken dark mode support on Mojave.

**Comment by craighurley** [comment]
keepassxc: 2.5.1
macos: 10.15.1

Tab titles colour and input fields colour look good for me in dark and light mode, even after chaning theme without restarting keepassxc.
