### ISSUE TITLE
the database hangs when saving fields

### ISSUE THREAD

**Issue by josemata00** [keepassxreboot/keepassxc#4813]
OS .: Windows 10, x64.
Browser: Chrome, with KeepassXC-Browser extension

When trying to save modifications to the database, there are occasions when said DB crashes and the app cannot be closed, without being able to lock the DB, but passwords can be recovered from chrome. the only way to solve is forcing it to close with the windows task manager. the problem is both x86 and x64 versions, and it's not just on a PC. It has the same fault on my other PC with the same OS.

![Sin título](https://user-images.githubusercontent.com/16071024/83576264-57826300-a4ff-11ea-8cde-1c7425f2ba7c.png)

**Comment by droidmonkey** [comment]
Fixed already in next release

**Comment by josemata00** [comment]
Can I access this version? I really LOVE KeepassXC a lot and how it
integrates beautifully with Chrome ... It can be a beta version, which will
then update when you upload the stable version.

*José Mata*

NOTA CONFIDENCIAL: La informacion contenida en este correo electronico es
confidencial y solo puede ser utilizada por la persona o la compania a la
cual esta dirigido y/o por el emisor. Si no es el receptor autorizado,
cualquier retencion, difusion, distribucion o copia de este mensaje es
prohibida y sera sancionada por la ley. Si por error recibe este mensaje,
favor reenviarlo al emisor y borrar el mensaje recibido inmediatamente

**Comment by droidmonkey** [comment]
Https://snapshot.keepassxc.org

**Comment by boozezela** [comment]
I still have this issue with KeepassXC  2.6.1 on Windows 10 2004.

When saving changes to the DB the whole interface just stays greyed out. The program does not crash or display any error message though.

**Comment by droidmonkey** [comment]
You seem to have a lot of random issues, make sure virus scanner or similar is not interfering.

**Comment by boozezela** [comment]
I'll do thanks. Although some of the issues I have reported are cross-platform and affect different version combinations.
