### ISSUE TITLE
Database selector bad icons theme

### ISSUE THREAD

**Issue by medmedin2014** [keepassxreboot/keepassxc#5593]
When I set the app to use native theme (which is dark breeze theme) I get bad icons on database selector. Is there no way to use the dark breeze icons inside the app because the shipped icons look ugly.

```
keepassxc : 2.6.1
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.15.1
Kernel Version: 5.4.72-1-MANJARO
OS Type: 64-bit
```

![Screenshot_20201023_111910](https://user-images.githubusercontent.com/7027319/96992532-f137c480-1521-11eb-914c-5aa02e381ca0.png)

**Comment by medmedin2014** [comment]
The keepassxc dark theme has same trouble
![Screenshot_20201023_112452](https://user-images.githubusercontent.com/7027319/96992868-65726800-1522-11eb-80d9-73616a8a6ea2.png)

**Comment by droidmonkey** [comment]
Looks like a theme issue on your end since they are dark even when using classic theme (which is qt default). Plus we dont provide those icons at all, they are provided by your desktop env.

**Comment by medmedin2014** [comment]
@droidmonkey  No, it's not KDE theme problem, here are some comparaisons
![Screenshot_20201023_115210](https://user-images.githubusercontent.com/7027319/96995662-70c79280-1526-11eb-99f3-ee85ea78cbbc.png)
![Screenshot_20201023_115308](https://user-images.githubusercontent.com/7027319/96995673-758c4680-1526-11eb-82ba-b9462b82c79e.png)

**Comment by medmedin2014** [comment]
@droidmonkey It seems keepassxc picks the light icons theme instead of the dark one.

**Comment by droidmonkey** [comment]
We don't own the file open dialog. You'll have to take this up with qt

**Comment by droidmonkey** [comment]
Perhaps there is some obscure function call to declare the theme as "dark"

**Comment by medmedin2014** [comment]
Apart from file selector, there other icons issues using native kde theme
![image12](https://user-images.githubusercontent.com/7027319/96997078-f51b1500-1528-11eb-8d52-63aeaae0a228.png)
![gg](https://user-images.githubusercontent.com/7027319/96997433-ae79ea80-1529-11eb-86fb-a898ddb959dd.png)
![tt](https://user-images.githubusercontent.com/7027319/96997457-b89be900-1529-11eb-8208-f91d8cccc852.png)

**Comment by droidmonkey** [comment]
Yah those are qt icons

**Comment by phoerious** [comment]
I fixed the icon issue in dialogues a while ago by using the system theme as fallback. Perhaps the theme is not complete.

**Comment by medmedin2014** [comment]
@phoerious KDE dark breeze icons appears correclty on other qt/gtk apps.

**Comment by iyanmv** [comment]
I recently did a fresh installation of Archlinux with Plasma. Before I never run into this issue, but now it happens to me every time. Going to icons configuration, switching to Breeze and then back to Breeze dark seems to fix the issue. But only temporarily. Any ideas?

**Comment by DMyachin** [comment]
I have same problem in Arch with Plasma

**Comment by medmedin2014** [comment]
Still the same problem with Plasma 5.21.5, both GTK and Qt apps pick the correct icons, only KeepassXC doesn't

![text843](https://user-images.githubusercontent.com/7027319/120047727-328ad800-c00d-11eb-929d-953806cb2c48.png)

**Comment by iyanmv** [comment]
Yep, I only notice this issue whenever I do a fresh installation and I have to open the database for the first time, but it's still there. And I wouldn't say is a Plasma/Qt bug since KeePassXC is literally the only app where I observe this.

**Comment by iyanmv** [comment]
> Yah those are qt injected icons

Are you sure? I don't think so...

**Comment by droidmonkey** [comment]
I have tested KDE extensively with various themes and it looks fine in newer versions. Closing this.

**Comment by medmedin2014** [comment]
@droidmonkey I still have the problem with Dark and Classic (platform-native) themes on:

```
KeePassXC: 2.7.6
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.4.11-2-MANJARO (64-bit)
Graphics Platform: Wayland
```
https://i.imgur.com/fGwRPRk.png

**Comment by droidmonkey** [comment]
![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/58b197f6-8b4c-4240-80fb-28f9b716c9b6)

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/8d6e60b8-948c-48c9-ae23-4dfe9a340e16)

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/7d0ea6aa-47cc-468b-b556-f9f9ede2e0b4)

Using flatpak distribution, both dark and classic theme work fine. We are not going to invest any more time in trying to solve this for specific configurations.

**Comment by medmedin2014** [comment]
@droidmonkey I'm using the native version and not the flatpak one,  and it seems in your screenshot KeePassXC uses the KDE portal like it was not a pure Qt app, the portal dialogs are only used by GTK apps to force them use Qt dialogs instead of using GTK ones.

**Comment by medmedin2014** [comment]
@droidmonkey A flatpak is not the perfect distribution package for testing, because like snaps it's just a specific type of packaging forced by Fedora on its own distribution.

**Comment by droidmonkey** [comment]
Flatpak is a great means to test because you can control more variables using Flatpak which makes it a superior distribution method across Linux distributions. I do recommend you switch to flatpak to solve this problem immediately.

I was able to reproduce with native build:

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/e6a37e20-eb43-4f9a-b2d9-92e479f05dbe)

**Comment by medmedin2014** [comment]
@droidmonkey Flatpaks and snaps have long history of slow performance, weird behaviors and difficulties to match their looks to the global applied theme, so many hacks are added to their configurations to fix those unnecessary problems. For me, it's recommended to avoid them for any rigorous testing.

**Comment by nicolasfella** [comment]
The problem here is the call to `QIcon::setThemeName("application")`. By setting a non-default icon theme Qt will stop using the platform's native icon engine (https://codebrowser.dev/qt5/qtbase/src/gui/image/qicon.cpp.html#1312).

Plasma's icon engine is what makes the icons have the correct colors when using a dark color scheme

**Comment by CelDaemon** [comment]
`QT_QPA_PLATFORMTHEME=xdgdesktopportal` seems to fix this issue for now by using the XDG portal instead, has there been any progress on finding a more proper solution?

**Comment by droidmonkey** [comment]
Qt6 probably

**Comment by droidmonkey** [comment]
Qt6 probably

**Comment by CelDaemon** [comment]
> Qt6 probably

I see, is it already possible to build with Qt6, or is that still in the works?

**Comment by droidmonkey** [comment]
Still in the works.

**Comment by Danny3** [comment]
Can't the program just use the KDE file picker / chooser, similar to how many Qt and even a few popular GTK based programs can do?
Krita, Qbittorrent and Firefox can do it properly!

Plasma is also becoming the most popular / used desktop environment for Linux:
https://pkgstats.archlinux.de/fun/Desktop%20Environments/history
So it's a real shame to not support it properly by using its really great file picker / chooser, which can also display the custom location that you have set in Dolphin by dragging locations to the left locations panel, besides showing thumbnails and other features.

**Comment by phoerious** [comment]
We do, but the theming bleeds over.

**Comment by Danny3** [comment]
From what I can see on a weekly build of Debian 14 (codename Forky, AKA the 'testing' repository) that comes with:
KDE Plasma Version: 6.6.5
KDE Frameworks Version: 6.23.0
Qt Version: 6.10.2

I see that the 2.7.10 version of the program, About -> Debug info, that is using or has been built with: Qt 5.15.17.

Is this the main or a big problem, that the program still uses Qt 5 while Plasma and most of other software have been ported to Qt 6?

Besides the filepicker not being the native KDE that is used, I see the dark theme working, but a bit different than the rest of Plasma, which I assume is using Breeze Dark at night.
The program's theme seems to be dark brown and dark gray from what I can tell, pretty similar to the prinscreens above.
Not as close to the default dark theme of Plasma as Qbittorrent, which is pretty much indistinguishable from other KDE programs.
IIRC, I think Plasma developers also mentioned in some news or blog post in the past that they made the dark theme of Plasma a bit darker in recent versions, so that may be a thing too why the difference is so big now and I don't even have an OLED or a very good screen anyway.

In case you have trouble porting to program to Qt6, maybe you can look at Qbittorrent's code, which also did a port from Qt 5 to 6 and both the theme and the file picker works perfectly in it, besides other Wayland related things, like scaling.
I think you can even ask its developers for a bit of help if needed.

Thank you very much for all the work!

**Comment by droidmonkey** [comment]
We already ported to qt6, try a snapshot build: https://snapshot.keepassxc.org

**Comment by JohnLGalt** [comment]
I'm using the QT6 build on Gentoo (KDE6/Plasma, Wayland, and systemd) and KPXC uses my native KDE theme _almost_ perfectly.

The aforementioned graphics on buttons like Open and Close when using the file dialog are still very faint because of being dark on dark buttons.

**Comment by Danny3** [comment]
> We already ported to qt6, try a snapshot build: https://snapshot.keepassxc.org

Great to hear that the port is already done and you have snapshots ready to test, even in the easiest format, which for me is AppImage.
I downloaded the 'KeePassXC-2.8.0-snapshot-x86_64.AppImage' from here (one below the latest folder, so it's easy to tell which build exactly):
https://snapshot.keepassxc.org/build-287114/
And after confirming 2 prompts, it just doesn't start.
I tried multiple times and even check if it has the execute permission which it has.
Finally I tried it to open it from terminal, where it gives this output:
```
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information

```
To be sure that this is not a new problem, I tried the 'KeePassXC-2.7.12-x86_64.appimage' file too and it shows the same error.
MKVToolnix and Moonlight seem to have the same problem.
GPU-T and MPC-Qt doesn't seem to have the same problem as they open just fine.

I guess the newer version of Debian weekly builds might have changed something for AppImage files as I don't remember having any problems with opening this kind of files in the past.
Fuse 3 is already installed: `fuse3 is already the newest version (3.18.2-2).`
And Fuse package will actually look like it's installing someghint new, but it's still Fuse 3 and it still doesn't solve anything:
```
sudo apt install fuse
Get:1 http://edited-local-mirror.country-code/debian forky/main amd64 fuse all 3.18.2-2 [16.0 kB]
Fetched 16.0 kB in 1s (27.7 kB/s)
Selecting previously unselected package fuse.
(Reading database… edited-thousands files and directories currently installed.)
Preparing to unpack …/archives/fuse_3.18.2-2_all.deb…
Unpacking fuse (3.18.2-2)…
Setting up fuse (3.18.2-2)…
```
There is no fuse2 package to install.
So at least at the moment I cannot test it until the Debian developers / maintainers figure out what they have broken for running AppImage files.

**Comment by JohnLGalt** [comment]
In Gentoo, I was able to get FUSE 2.x installed in a slotted install, so my system has **both** FUSE 2 (which some AppImages require) ***and*** FUSE 3 (which comes natively embedded with AppImages that use it). 

> john in ~
> ➜ eix sys-fs/fuse
> [I] sys-fs/fuse
>      Available versions:
>      (0)    2.9.9-r2                          <----- slot 0
>      (3)    3.18.2(3/4)^t                 <----- slot 3
>        {examples io-uring static-libs +suid systemtap test ABI_MIPS="n32 n64 o32" ABI_S390="32 64" ABI_X86="32 64 x32"}
>      Installed versions:  2.9.9-r2(16:53:02 03/21/26)(-examples -static-libs) 3.18.2(3/4)^t(05:27:20 04/06/26)(suid -io-uring -systemtap -test ABI_MIPS="-n32 -n64 -o32" ABI_S390="-32 -64" ABI_X86="64 -32 -x32")
>      Homepage:            https://github.com/libfuse/libfuse
>      Description:         An interface for filesystems implemented in userspace

I don't know if your *nix can handle slotted installations , but if you already have FUSE 3 and need it, that might be what you need. 

FWIW - from my understanding, this only occurs on systems that have a local install of FUSE 3.x (or don't have FUSE installed at all).  I think that if you revert it to FUSE 2.x (after verifying you don't need 3.x for anything, naturally) you should be fine also. I need FUSE 3.x installed for other things, so the slot was the only way to get around using other appimages that are built requiring FUSE 2.x.

**Comment by Danny3** [comment]
I don't how how to revert to FUSE 2.x since there is no fuse2 package and the fuse one also points to FUSE 3.x.
Since this is not such a big problem, I think I will just wait until the new version of the program comes to the repositories.
It's a shame that I cannot help with testing sooner though.

**Comment by JohnLGalt** [comment]
Ahhh, yeah, having the ability to install FUSE 2.x at all is a factor I didn't account for. My bad.

**Comment by Danny3** [comment]
No problem, not your fault!
Even though I'm a huge AppImage and Debian fan, sometimes they take strange decisions.
I still don't get why the AppImage developers don't move or at least support FUSE 3.
And who knows, maybe Debian developers / maintainers too by trying to make harder to install FUSE 2, if this is what is going on.
I wonder though why some AppImages work.
Could they have an embedded FUSE 2?

**Comment by JohnLGalt** [comment]
I've actually posed the same question to a developer of another app dev whose AppImage gave me the same "requires FUSE 2.x installed" message in his Discord. When he replies, if it is relevant, I'll post back here. There may be a valid reason - even if it is the fact that, when built against FUSE 3, which then embeds relevant files directly in the .AppImage file, it becomes much, much larger in size lol.

As for an embedded FUSE 2, it would certainly make sense - and in fact, might be something that the AppImage maintainers might need to look at - stop embedding FUSE 3 and start embedding FUSE 2 since 3 is the _de facto_ stable release.

**Comment by Danny3** [comment]
Great that you asked and I think it would be nice to post it here too if it's relevant.
I've done a little test trying to open many AppImage files to see which ones actually open, in case you or other people want to ask their developers how they built them, what they embedded and these are the ones that opened fine:

AudioWave-x86_64.appimage
GPU-T-0.1.2-x86_64.appimage
GPU-T-0.1.4-x86_64.appimage (this doesn't show its embedded icon anymore for which I opened a bug and they told me it's now using a new filesystem, Dwarfs, which is smaller and faster, see: https://github.com/lseurttyuu/GPU-T/issues/56)
kprotect-ui_0.1.0-beta_amd64.appimage
mpc-qt-linux-x64-26.01.appimage
qTox-v1.18.3-x86_64.appimage
RetroArch-Linux-x86_64.AppImage (impressive also how fast it opens after I click Launch)
rpcs3-v0.0.39-18705-0f85e912_linux64.appimage
simplex-desktop-x86_64.appimage
trifa-material-x86_64-v1.0.56.appimage

**Comment by JohnLGalt** [comment]
Actually, the Appimage.org website has a lot of good information.

Specifically, this section:  https://docs.appimage.org/user-guide/troubleshooting/fuse.html#setting-up-fuse-2-x-alongside-of-fuse-3-x-on-recent-ubuntu-22-04-debian-and-their-derivatives

And, they have a fallback section if FUSE (2) refuses to install / cannot be installed.

https://docs.appimage.org/user-guide/troubleshooting/fuse.html#fallback-if-fuse-can-t-be-made-working

That whole page should be enough info for you to take a stab at trying the KPXC AppImage again. And all of those others, as well lol.

**Comment by Danny3** [comment]
The `sudo apt install libfuse2` doesn't work:
```
Package libfuse2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```
But as usual with Debian and APT, it doesn't say which other packages.
And the `./KeePassXC-2.8.0-snapshot-x86_64.appimage --appimage-extract-and-run` crashed immediately showing:
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

```
And a notification whose details are these:
```
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
           PID: 23889 (keepassxc)
           UID: 1000 (edited-username)
           GID: 1000 (edited-username)
        Signal: 6 (ABRT)
     Timestamp: Sun 2026-06-07 19:27:26 EEST (4s ago)
  Command Line: keepassxc
    Executable: /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/bin/keepassxc
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.kde.konsole-23669.scope/tab(23688).scope
          Unit: user@1000.service
     User Unit: app-org.kde.konsole-23669.scope
         Slice: user-1000.slice
     Owner UID: 1000 (edited-username)
       Boot ID: f8e8664fcc7c463ca67fb44bd1c0a790
    Machine ID: d4c26682cabe4bb1975c9e88aa01bce6
      Hostname: LD1
       Storage: /var/lib/systemd/coredump/core.keepassxc.1000.f8e8664fcc7c463ca67fb44bd1c0a790.23889.1780849646000000.zst (present)
  Size on Disk: 1.9M
       Message: Process 23889 (keepassxc) of user 1000 dumped core.
                
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/bin/keepassxc without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/bin/keepassxc
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libgcrypt.so.20 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libgcrypt.so.20
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libcap.so.2 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libcap.so.2
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/liblz4.so.1 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/liblz4.so.1
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libcrypto.so.3 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libcrypto.so.3
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libgomp.so.1 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libgomp.so.1
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libicudata.so.70 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libpcre.so.3 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libpcre.so.3
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libbrotlicommon.so.1 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libkrb5support.so.0 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libkrb5support.so.0
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libk5crypto.so.3 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libk5crypto.so.3
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libsystemd.so.0 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libsystemd.so.0
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libsqlite3.so.0 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libsqlite3.so.0
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/liblzma.so.5 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/liblzma.so.5
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libpcre2-16.so.0 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libpcre2-16.so.0
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libb2.so.1 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libb2.so.1
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libdouble-conversion.so.3 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libdouble-conversion.so.3
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libicuuc.so.70 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libicuuc.so.70
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libicui18n.so.70 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libicui18n.so.70
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libmd4c.so.0 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libmd4c.so.0
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libpng16.so.16 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libpng16.so.16
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libxkbcommon.so.0 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libxkbcommon.so.0
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libglib-2.0.so.0 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libglib-2.0.so.0
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libgssapi_krb5.so.2 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libgssapi_krb5.so.2
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libzstd.so.1 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libzstd.so.1
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libproxy.so.1 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libproxy.so.1
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libbotan-2.so.19 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libbotan-2.so.19
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libminizip.so.1 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libminizip.so.1
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libbrotlidec.so.1 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libdbus-1.so.3 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libdbus-1.so.3
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libkeyutils.so.1 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libkeyutils.so.1
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libzxcvbn.so.0 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libpcsclite.so.1 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libpcsclite.so.1
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libqrencode.so.4 without build-id.
                Module /tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libqrencode.so.4
                Module libudev.so.1 from deb systemd-260.1-1.amd64
                Module libgcc_s.so.1 from deb gcc-16-16.1.0-1.amd64
                Module libstdc++.so.6 from deb gcc-16-16.1.0-1.amd64
                Stack trace of thread 23889:
                #0  0x00007f870629fcfc __pthread_kill_implementation (libc.so.6 + 0x97cfc)
                #1  0x00007f8706248d02 __GI_raise (libc.so.6 + 0x40d02)
                #2  0x00007f87062304b2 __GI_abort (libc.so.6 + 0x284b2)
                #3  0x00007f8706eb2203 n/a (/tmp/appimage_extracted_2fcea493e0541a724b0e4419631a5780/usr/lib/libQt6Core.so.6 + 0xa3203)
                #4  0x0000000000000000 n/a (n/a + 0x0)
                ELF object binary architecture: AMD x86-64

```
The `./KeePassXC-2.8.0-snapshot-x86_64.appimage --appimage-extract` seeems to work fine.
But the `squashfs-root/AppRun` seems to give again a "service crash" notification and in the terminal:
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted                    (core dumped) squashfs-root/AppRun
```
I'm sorry, but I give up here as there seems too much trouble for the time that I have.
I guess that the Debian developers or somebody else will fix these problems in the future.
I'll wait for the updates of the program in the normal (native) repositories (unstable, testing, stable) of Debian.
Thank you for all the help!

**Comment by droidmonkey** [comment]
The platform plugin issue is new with qt6 appimage builds. We are trying to figure out why that is happening.

**Comment by JohnLGalt** [comment]
welp - progress. We now know that there is an inherent platform plugin issue with the move to QT6, which, incidentally, the package (direct merge) I'm using in Gentoo doesn't exhibit. I have both FUSE types installed also, and I could readily give the AppImage a shot and see if it throws the same error over here. I'll report back.

We also know that the AppImages are being built as v1 versus v2 (according to the AppImage documentation). I'm going to explore that side of it more and see if there is any real difference in terms of the build type in an AppImage going by their own documentation. Let's see what I can discover there.

**Comment by JohnLGalt** [comment]
I got similar results from the AppImage. @droidmonkey I captured both the notification details like @Danny3 but also the output of gdb run from the crash dialog, but it is long, and completely unrelated to this topic. Are you all tracing the platform plugin bug somewhere else, and would either of those I captured be of any help to you?

**Comment by droidmonkey** [comment]
@JohnLGalt https://github.com/keepassxreboot/keepassxc/issues/13353
