### ISSUE TITLE
Unplugging, replugging monitor makes window distort

### ISSUE THREAD

**Issue by xpusostomos** [keepassxreboot/keepassxc#6262]
## Overview
I have a laptop that from time to time I plug in an external monitor. Sometimes I find the Keepass app with the bottom right pane (with the General, Advanced and Autotype tabs) inaccessable because the window resizing seems broken in this situation.

## Steps to Reproduce
1.  Plugin external monitor
2.  start up keepassxc
3.  login to keepass
4. minimise keepass
5. unplug monitor
6. replug monitor
7. open keepass window
8. window is distorted.
9. at this point, no amount of resizing the window can save it. It has to be restarted.

## Expected Behavior
External monitors should work

## Actual Behavior
See screenshot here with bottom right pane hidden
![Capture](https://user-images.githubusercontent.com/45857005/110711604-f177f880-8253-11eb-9227-1ded010b3125.PNG)

## Context

KeePassXC - 2.6.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by gheja** [comment]
By any chance do you use [UI scaling](https://www.lifewire.com/using-windows-10-display-scaling-4587328) in Windows? (Might be a default setting for bigger displays.)

Are you using multiple displays with different scales?

Does checking/unchecking View > Compact Mode in KeepassXC change anything?

**Comment by xpusostomos** [comment]
I do have scaling turned on, on my laptop display (125%). You're right, the problem doesn't seem to happen when I change my laptop display to 100%

Since I made this bug report, I'm now on Windows 11. The problem still exists.

Yes, the problem happens with compact mode.

**Comment by droidmonkey** [comment]
Use View -> Always on Top to recreate the main window, should fix it. Could also hide to tray and restore or maximize the window to the display.

**Comment by JohnLGalt** [comment]
I had a few Environment variables set in Windows (both 10 and 11) that helped fix QT 5.x-based apps, But a recent build of Windows 11 made those all kinds of whacked.

Still, here they are:

variable name QT_SCALE_FACTOR
variable value 1

Variable name: QT_AUTO_SCREEN_SCALE_FACTOR
Variable value: 0

Variable name: QT_SCREEN_SCALE_FACTORS
Variable value: 2

I suspect that I may add these back in because it was still better than what I get now without them in place.

**Comment by xpusostomos** [comment]
@droidmonkey if by "hide to tray" you mean minimise to the taskbar, that doesn't help. The view menu is non-functional when the problem appears also. You can actually access the view menu after maximizing, (maximizing doesn't fix it, but it does make the menu work) but that means you've got 6  button presses, maximize, turn on always on top. turn off always on top, unmaximize.... versus two buttons to kill it and relaunch again.

**Comment by droidmonkey** [comment]
That level of broken is 100% Qt. I meant to the system tray icon, not just minimize. If the tray icon is enabled you can press Ctrl+Shift+M to totally hide the main window. When you show it again it will be completely redrawn. 

I wonder if we can detect when the screen scale changes and force a relayout to occur.

**Comment by JohnLGalt** [comment]
Yeah, it's 100% Qt, because it isn't just KPXC doing it - I get the exact same behavior in a couple of apps, all of them only have one thing in common - Qt. 

Putting in the fixes I noted above seems to have fixed it for the most part again. It's only been a few hours though, so more testing is needed.
